#!/usr/bin/env bash
# =============================================================================
# generate_litellm_runtime_keys.sh
#
# Generate local LiteLLM runtime keys for Route B-light secret population.
# Writes shell export statements to an ignored *.env file by default.
#
# Security:
#   - Does not print generated key values.
#   - Output file should remain local and ignored by git.
#   - Use `source <output-file>` before running populate_litellm_runtime_values.sh.
# =============================================================================

set -euo pipefail

DEFAULT_OUTPUT="infra/aws/envs/route-b-light.keys.env"
OUTPUT="${DEFAULT_OUTPUT}"
FORCE=""

usage() {
  cat <<EOF
Usage: $(basename "$0") [--output <path>] [--force] [--help]

Generate LITELLM_MASTER_KEY and LITELLM_SALT_KEY into a local env file.

Arguments:
  --output <path>  Output env file path (default: ${DEFAULT_OUTPUT})
  --force          Overwrite output file if it already exists
  --help           Show this help message

Example:
  ./scripts/aws/generate_litellm_runtime_keys.sh
  source infra/aws/envs/route-b-light.keys.env
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -e "${OUTPUT}" && -z "${FORCE}" ]]; then
  echo "ERROR: Output file already exists: ${OUTPUT}" >&2
  echo "Use --force to overwrite, or choose a different --output path." >&2
  exit 1
fi

random_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${bytes}"
  else
    python3 - "${bytes}" <<'PYEOF'
import secrets, sys
print(secrets.token_hex(int(sys.argv[1])))
PYEOF
  fi
}

mkdir -p "$(dirname "${OUTPUT}")"

MASTER_KEY="sk-$(random_hex 32)"
SALT_KEY="$(random_hex 32)"

# Restrict permissions for newly-created file.
umask 077
cat >"${OUTPUT}" <<EOF
# Generated by scripts/aws/generate_litellm_runtime_keys.sh
# Do not commit this file. It is ignored by *.env in .gitignore.
export LITELLM_MASTER_KEY='${MASTER_KEY}'
export LITELLM_SALT_KEY='${SALT_KEY}'
EOF
chmod 600 "${OUTPUT}"

# Validate without printing key values.
if [[ ! "${MASTER_KEY}" =~ ^sk-[0-9a-f]{64}$ ]]; then
  echo "ERROR: Generated LITELLM_MASTER_KEY failed format validation." >&2
  exit 1
fi
if [[ ! "${SALT_KEY}" =~ ^[0-9a-f]{64}$ ]]; then
  echo "ERROR: Generated LITELLM_SALT_KEY failed format validation." >&2
  exit 1
fi

mode="$(stat -c '%a' "${OUTPUT}" 2>/dev/null || stat -f '%Lp' "${OUTPUT}")"
if [[ "${mode}" != "600" ]]; then
  echo "ERROR: Output file permission is ${mode}, expected 600." >&2
  exit 1
fi

echo "Generated LiteLLM runtime keys."
echo "Output file: ${OUTPUT}"
echo "Validation: PASS (values hidden; master prefix/length and salt length verified)"
echo "Permissions: ${mode}"
echo "Next: source ${OUTPUT}"
